import asyncio
from typing import Any, AsyncGenerator, List
from src.crewai_core.domain.interfaces.llm import ILLMProvider, LLMMessage, LLMResponse


class MockLLMAdapter(ILLMProvider):
    """Mock LLM Adapter for fast unit testing, CI/CD, and local offline runs."""

    def __init__(self, predefined_response: str = "This is a high-quality response generated by MockLLMAdapter."):
        self.predefined_response = predefined_response

    async def generate(self, messages: List[LLMMessage], **kwargs: Any) -> LLMResponse:
        # Simulate slight network delay
        await asyncio.sleep(0.01)
        last_message = messages[-1].content if messages else ""
        content = f"{self.predefined_response}\n\n[Processed Task with {len(messages)} messages. Last context length: {len(last_message)} chars]"

        return LLMResponse(
            content=content,
            token_usage={"prompt_tokens": 120, "completion_tokens": 45, "total_tokens": 165},
            finish_reason="stop",
        )

    async def generate_stream(self, messages: List[LLMMessage], **kwargs: Any) -> AsyncGenerator[str, None]:
        for word in self.predefined_response.split(" "):
            await asyncio.sleep(0.005)
            yield word + " "
