import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, BASE_DIR)

from config import (
    BASE_DIR, DATA_DIR, HISTORY_FILE, ACCOUNTS_FILE, ACCOUNTS_EXAMPLE_FILE,
    SETTINGS_FILE, SETTINGS_EXAMPLE_FILE, COOKIES_FILE,
    ASSETS_DIR, FONTS_DIR, PRESETS_DIR, AUDIOS_DIR, OVERLAYS_DIR, DEFAULT_FONT_PATH,
    STORAGE_DIR, STORAGE_INPUT_DIR, STORAGE_OUTPUT_DIR, TEMP_DIR, LOGS_DIR,
    VIDEO_DIR, OUTPUT_BASE_DIR, BIN_DIR, FFMPEG_EXE as FFMPEG_PATH, FFPROBE_EXE as FFPROBE_PATH
)

DEFAULT_SOURCE_DIR = VIDEO_DIR
DEFAULT_DEST_DIR = OUTPUT_BASE_DIR

